export const SCHEDULE_CHECK_PROXIES = 'SCHEDULE_CHECK_PROXIES';
export const SCHEDULE_CHECK_COOKIES = 'SCHEDULE_CHECK_COOKIES';
export const SCHEDULE_GENERATE_ALL_COOKIE = 'SCHEDULE_GENERATE_ALL_COOKIE';

export const MQ_CHECK_PROXY = 'MQ_CHECK_PROXY';
export const MQ_CHECK_COOKIE = 'MQ_CHECK_COOKIE';
export const MQ_COUNT_COOKIE = 'MQ_COUNT_COOKIE';
export const MQ_GENERATE_ONE_COOKIE = 'MQ_GENERATE_ONE_COOKIE';
