export const SCHEDULE_CRAWL_ANIME_ES_LATEST_EPISODE = 'SCHEDULE_CRAWL_ANIME_ES_LATEST_EPISODE';

export const SCHEDULE_SYNC_ANIME_ES_ALL_ANIME = 'SCHEDULE_SYNC_ANIME_ES_ALL_ANIME';
export const SCHEDULE_SYNC_ANIME_ES_ALL_EPISODE = 'SCHEDULE_SYNC_ANIME_ES_ALL_EPISODE';

export const MQ_CRAWL_ANIME_ES_ALL_ANIME = 'MQ_CRAWL_ANIME_ES_ALL_ANIME';
export const MQ_CRAWL_ANIME_ES_LATEST_EPISODE = 'MQ_CRAWL_ANIME_ES_LATEST_EPISODE';
export const MQ_CRAWL_ANIME_ES_ANIME_BY_SLUG = 'MQ_CRAWL_ANIME_ES_ANIME_BY_SLUG';
export const MQ_CRAWL_ANIME_ES_ALL_ANIME_OF_PAGE = 'MQ_CRAWL_ANIME_ES_ALL_ANIME_OF_PAGE';
export const MQ_CRAWL_ANIME_ES_EPISODE_BY_SLUG = 'MQ_CRAWL_ANIME_ES_EPISODE_BY_SLUG';
export const MQ_CRAWL_ANIME_ES_POPULAR_ANIME = 'MQ_CRAWL_ANIME_ES_POPULAR_ANIME';
export const MQ_CRAWL_ANIME_ES_POPULAR_ANIME_OF_PAGE = 'MQ_CRAWL_ANIME_ES_POPULAR_ANIME_OF_PAGE';
export const MQ_CRAWL_ANIME_ES_RECENT_ANIME_EPISODE = 'MQ_CRAWL_ANIME_ES_RECENT_ANIME_EPISODE';
export const MQ_CRAWL_ANIME_ES_RECENT_ANIME_EPISODE_OF_PAGE = 'MQ_CRAWL_ANIME_ES_RECENT_ANIME_EPISODE_OF_PAGE';

export const MQ_SYNC_ANIME_ES_ALL_EPISODE = 'MQ_SYNC_ANIME_ES_ALL_EPISODE';
export const MQ_SYNC_ANIME_ES_EPISODE = 'MQ_SYNC_ANIME_ES_EPISODE';

export const MQ_SYNC_ANIME_ES_ALL_ANIME = 'MQ_SYNC_ANIME_ES_ALL_ANIME';
export const MQ_SYNC_ANIME_ES_ANIME = 'MQ_SYNC_ANIME_ES_ANIME';

export const MQ_SYNC_ANIME_ES_GENRE = 'MQ_SYNC_ANIME_ES_GENRE';
