export const SCHEDULE_CRAWL_LATEST_STAR = 'SCHEDULE_CRAWL_LATEST_STAR';

export const SCHEDULE_CRAWL_LATEST_EPISODE = 'SCHEDULE_CRAWL_LATEST_EPISODE';

export const SCHEDULE_SYNC_ALL_STAR = 'SCHEDULE_SYNC_ALL_STAR';
export const SCHEDULE_SYNC_ALL_MOVIE = 'SCHEDULE_SYNC_ALL_MOVIE';
export const SCHEDULE_SYNC_ALL_EPISODE = 'SCHEDULE_SYNC_ALL_EPISODE';

export const MQ_CRAWL_ALL_STAR = 'MQ_CRAWL_ALL_STAR';
export const MQ_CRAWL_ALL_STAR_OF_PAGE = 'MQ_CRAWL_ALL_STAR_OF_PAGE';
export const MQ_CRAWL_STAR_BY_SLUG = 'MQ_CRAWL_STAR_BY_SLUG';

export const MQ_CRAWL_ALL_MOVIE = 'MQ_CRAWL_ALL_MOVIE';
export const MQ_CRAWL_LATEST_EPISODE = 'MQ_CRAWL_LATEST_EPISODE';
export const MQ_CRAWL_MOVIE_BY_SLUG = 'MQ_CRAWL_MOVIE_BY_SLUG';

export const MQ_CRAWL_EPISODE_BY_SLUG = 'MQ_CRAWL_EPISODE_BY_SLUG';

export const MQ_SYNC_ALL_STAR = 'MQ_SYNC_ALL_STAR';
export const MQ_SYNC_STAR = 'MQ_SYNC_STAR';

export const MQ_SYNC_STAR_MOVIE = 'MQ_SYNC_STAR_MOVIE';

export const MQ_SYNC_ALL_MOVIE = 'MQ_SYNC_ALL_MOVIE';
export const MQ_SYNC_MOVIE = 'MQ_SYNC_MOVIE';

export const MQ_SYNC_ALL_EPISODE = 'MQ_SYNC_ALL_EPISODE';
export const MQ_SYNC_EPISODE = 'MQ_SYNC_EPISODE';

export const MQ_SYNC_GENRE = 'MQ_SYNC_GENRE';
export const MQ_SYNC_COUNTRY = 'MQ_SYNC_COUNTRY';

export const MQ_COUNT_VIEW_STAR = 'MQ_COUNT_VIEW_STAR';
export const MQ_COUNT_VIEW_MOVIE = 'MQ_COUNT_VIEW_MOVIE';
export const MQ_COUNT_VIEW_EPISODE = 'MQ_COUNT_VIEW_EPISODE';
