export const SCHEDULE_CRAWL_ANIME_EN_LATEST_EPISODE = 'SCHEDULE_CRAWL_ANIME_EN_LATEST_EPISODE';

export const SCHEDULE_SYNC_ANIME_EN_ALL_ANIME = 'SCHEDULE_SYNC_ANIME_EN_ALL_ANIME';
export const SCHEDULE_SYNC_ANIME_EN_ALL_EPISODE = 'SCHEDULE_SYNC_ANIME_EN_ALL_EPISODE';

export const MQ_CRAWL_ANIME_EN_ALL_ANIME = 'MQ_CRAWL_ANIME_EN_ALL_ANIME';
export const MQ_CRAWL_ANIME_EN_LATEST_EPISODE = 'MQ_CRAWL_ANIME_EN_LATEST_EPISODE';
export const MQ_CRAWL_ANIME_EN_ANIME_BY_SLUG = 'MQ_CRAWL_ANIME_EN_ANIME_BY_SLUG';
export const MQ_CRAWL_ANIME_EN_ALL_ANIME_OF_PAGE = 'MQ_CRAWL_ANIME_EN_ALL_ANIME_OF_PAGE';
export const MQ_CRAWL_ANIME_EN_EPISODE_BY_SLUG = 'MQ_CRAWL_ANIME_EN_EPISODE_BY_SLUG';
export const MQ_CRAWL_ANIME_EN_POPULAR_ANIME = 'MQ_CRAWL_ANIME_EN_POPULAR_ANIME';
export const MQ_CRAWL_ANIME_EN_POPULAR_ANIME_OF_PAGE = 'MQ_CRAWL_ANIME_EN_POPULAR_ANIME_OF_PAGE';
export const MQ_CRAWL_ANIME_EN_CHINESE_ANIME_EPISODE = 'MQ_CRAWL_ANIME_EN_CHINESE_ANIME_EPISODE';
export const MQ_CRAWL_ANIME_EN_CHINESE_ANIME_EPISODE_OF_PAGE = 'MQ_CRAWL_ANIME_EN_CHINESE_ANIME_EPISODE_OF_PAGE';
export const MQ_CRAWL_ANIME_EN_RECENT_ANIME_EPISODE = 'MQ_CRAWL_ANIME_EN_RECENT_ANIME_EPISODE';
export const MQ_CRAWL_ANIME_EN_RECENT_ANIME_EPISODE_OF_PAGE = 'MQ_CRAWL_ANIME_EN_RECENT_ANIME_EPISODE_OF_PAGE';

export const MQ_SYNC_ANIME_EN_ALL_EPISODE = 'MQ_SYNC_ANIME_EN_ALL_EPISODE';
export const MQ_SYNC_ANIME_EN_EPISODE = 'MQ_SYNC_ANIME_EN_EPISODE';

export const MQ_SYNC_ANIME_EN_ALL_ANIME = 'MQ_SYNC_ANIME_EN_ALL_ANIME';
export const MQ_SYNC_ANIME_EN_ANIME = 'MQ_SYNC_ANIME_EN_ANIME';

export const MQ_SYNC_ANIME_EN_GENRE = 'MQ_SYNC_ANIME_EN_GENRE';

export const MQ_SYNC_ANIME_EN_SUB_CATEGORY = 'MQ_SYNC_ANIME_EN_SUB_CATEGORY';

export const MQ_COUNT_ANIME_EN_VIEW_ANIME = 'MQ_COUNT_ANIME_EN_VIEW_ANIME';
export const MQ_COUNT_ANIME_EN_VIEW_EPISODE = 'MQ_COUNT_ANIME_EN_VIEW_EPISODE';
